### PR TITLE
Provide more fluent interface to handle boolean filter

### PR DESCRIPTION
**Pull request by heka1024**
It would be nice to be able to use a boolean filter like `<filter_name>?` instead of `<filter_name>`.

### CODE REVIEW

**Review by DevStarSJ — APPROVED** [review]
LGTM

**Comment by AaronLasseigne** [comment]
We used to generate predicate methods for each input to see if it was given. With that dropped in 4.0.0 we can do something like this now. It's also far enough away from what it used to do that I think I shouldn't mess up people upgrading.

**Comment by AaronLasseigne** [comment]
There are a couple of linting errors but I think this is a good idea.

**Comment by heka1024** [comment]
@AaronLasseigne I fixed linting errors. Could you review this PR once again?

**Comment by AaronLasseigne** [comment]
Thanks!

**Pull request merged**
