### PR TITLE
Start testing on active model 6.1

### PR DESCRIPTION
**Pull request by zjwhitehead**
Rails RC1 is out. 
Lets make sure its compatible

### CODE REVIEW

**Comment by zjwhitehead** [comment]
Looks like its failing with the same issue I was seeing in Rails 6.1

**Comment by AaronLasseigne** [comment]
Looks like `ActiveModel::Errors::CALLBACK_OPTIONS` isn't a thing anymore.

**Comment by mmoll** [comment]
I took the liberty to open this against the 4.0 branch in #490 and it's looking way better, maybe it's time for a new major release (or to rework the backport handling in 3.x)? 🚀

**Comment by zjwhitehead** [comment]
Related issue https://github.com/AaronLasseigne/active_interaction/issues/489

**Comment by kapso** [comment]
Any plans for releasing this soon?

**Comment by kapso** [comment]
This `::ActiveModel::Errors::CALLBACKS_OPTIONS` needs to be replaced with `::ActiveModel::Error::CALLBACKS_OPTIONS`

**Pull request closed without merging**
